### ISSUE TITLE
CEX spec 3.0 #!catalog example is misleading

### ISSUE THREAD

**Issue by ace280** [cite-architecture/citedx#12]
The [specification](https://github.com/cite-architecture/citedx/blob/master/docs/CEX-spec-3.0.md) has a small but crucial error. Even though the explanation features all 8 fields, including Number 8 (the language), the example line does not:

`#!ctscatalog
// comments omitted
urn#citationScheme#groupName#workTitle#versionLabel#exemplarLabel#online
urn:cts:greekLit:tlg5026.msA.hmt:#book,comment,section#Scholia Vetera in Iliadem#Main scholia to Venetus A#Homer Multitext##true#grc `

In other words: the line `urn#citationScheme#groupName#workTitle#versionLabel#exemplarLabel#online` should be
`urn#citationScheme#groupName#workTitle#versionLabel#exemplarLabel#online#lang`

I'm afraid that other projects such as openITI adopted the mistake. An example of this can be found  [here](https://github.com/OpenITI/i.cex/blob/master/data/JK000001-ara1-00200.cex). This should be fixed in the specification and projects should be contacted as programs such as the [cite microservices](https://github.com/cite-architecture/citemicroservices) will rely on correctly outlined CEX files.

**Comment by ace280** [comment]
This issue is replicated in some of the CEX files to be found here. The following CEX-files miss #lang in the first line in #!ctscatalog:
https://github.com/cite-architecture/citedx/blob/master/libraries/cite-test-enriched.cex
https://github.com/cite-architecture/citedx/blob/master/libraries/cite-test-huge.cex
https://github.com/cite-architecture/citedx/blob/master/libraries/iliads.cex
https://github.com/cite-architecture/citedx/blob/master/libraries/jane_austen.cex
https://github.com/cite-architecture/citedx/blob/master/libraries/metrical-summaries.cex

**Comment by neelsmith** [comment]
fixed.  Thanks for the clear description.
