### ISSUE TITLE
In docs, ctscatalog where it should read ctsdata?

### ISSUE THREAD

**Issue by nevenjovanovic** [cite-architecture/citedx#27]
The file docs/CEX-spec-3.0.1.md says, describing the ctsdata block:
```
Example: The following example is a valid ctscatalog block, using # for its delimiting string. It defines two citable nodes of text.
```
Shouldn't it read `ctsdata` instead of `ctscatalog`?

**Comment by ace280** [comment]
This seems to be a copy/paste error where the first sentence of the example was copied from the [ctscatalog example](https://github.com/cite-architecture/citedx/blob/master/docs/CEX-spec-3.0.1.md#ctscatalog), but the line was never adjusted for the [ctsdata example](https://github.com/cite-architecture/citedx/blob/master/docs/CEX-spec-3.0.1.md#ctsdata).

**Comment by ace280** [comment]
@nevenjovanovic I am creating an issue for this so they can merge easily.

**Comment by neelsmith** [comment]
Accepted pull request.  Bumping specification version to 3.0.2.
